print ("\n This is Going to be First Line \n" )
name = input (" Enter your Name : " )
col = input (" Enter your favourite Color : " )
print("\n Thank you \n")
print(name + " Your Color of the Day is " + col + "\n")
